import type { Job, TenantConfig } from "@/lib/types";

// Used as a dev fallback when Supabase env vars are missing, and as the
// canonical "demo" tenant content rendered at /u/demo. Mirrors the seed.sql.
export const demoTenant: TenantConfig = {
  id: "11111111-1111-1111-1111-111111111111",
  slug: "demo",
  status: "active",
  branding: {
    logoUrl: null,
    primaryColor: "#036ae5",
    themePreset: "thuy",
    fontFamily: "Be Vietnam Pro",
  },
  profile: {
    fullName: "Ms. Jane Doe",
    email: "jane.doe@example.com",
    avatarUrl: null,
    title: "Recruitment Specialist",
    yearsExperience: 5,
    specialty: "Talent Acquisition",
    tagline: "Connecting talents with the right opportunities",
    socials: {
      facebook: "https://facebook.com/",
      telegram: "https://t.me/",
      whatsapp: "https://wa.me/",
      linkedin: "https://linkedin.com/",
    },
    ctaUrl: "https://cal.com/your-handle/15min",
  },
  company: {
    name: "Acme Co",
    fullName: "Acme Co (State-of-the-Art-Technology)",
    sizeRange: "1000 - 2000",
    headquarter: "Hanoi, Vietnam",
    representativeOffices: "US, Japan, Korea and Australia",
    mainClients: "US & NA, EU, UK, ANZ, and Asia",
    description: "",
  },
  nav: [
    { href: "/", label: "List Jobs", enabled: true },
    { href: "/information", label: "Information", enabled: true },
    { href: "/benefits", label: "Benefits", enabled: true },
  ],
  ui: {
    showLocationsFilter: true,
    showLevelFilter: true,
    showCategoryFilter: true,
    locations: [],
    levels: [
      { value: "all", label: "All Level" },
      { value: "fresher", label: "Fresher" },
      { value: "intern", label: "Intern" },
      { value: "junior", label: "Junior" },
      { value: "middle", label: "Middle" },
      { value: "senior", label: "Senior" },
      { value: "leader", label: "Leader" },
      { value: "manager", label: "Manager" },
    ],
    categories: [
      { value: "back-office", label: "Back Office", keyword: "back office" },
      {
        value: "engineering",
        label: "Engineering & Technology",
        keyword: "engineering",
      },
      { value: "operation", label: "Operation Support", keyword: "operation" },
      { value: "sales", label: "Sales & Marketing", keyword: "sales" },
    ],
  },
  pages: {
    information: {
      visible: true,
      sections: [
        {
          title: "About us",
          body: "Acme Co offers leading tech experts with strong determination, enthusiasm and commitment to providing the most hi-tech IT services, with the ultimate goal to enable your business success through digital transformation.",
        },
        {
          title: "Our reach",
          body: "During 10+ years of development, we have gathered over 1000 talented IT consultants and developers who share deep expertise to successfully provide full-cycle IT services to our Clients from 30+ nations worldwide, with 500+ projects in various industries.",
        },
      ],
    },
    benefits: {
      visible: true,
      groups: [
        {
          title: "🎯 Flexible working regime and health care",
          bullets: [
            "Flexible timekeeping (from 8:00 - 9:00 to 17:30 - 18:30)",
            "Minimum 14 paid leaves per annum for all employees after probation",
            "01-day remote work per month",
            "Social insurance, health insurance, premium health care",
          ],
        },
        {
          title: "🎯 Transparent and fair benefits",
          bullets: [
            "Saturday & Sunday OFF, OT pay 150%/200%/300% per labor law",
            "Work performance review 2 times/year",
            "13th-month salary and performance-based bonus",
          ],
        },
        {
          title: "🎯 Dynamic environment and open culture",
          bullets: [
            "Year-end party, sports day, yearly company trip, quarterly team-building",
            "Monthly Happy Hour, free coffee/tea/drinks",
            "Allowance when joining clubs: Soccer, Swimming, Yoga, Music",
          ],
        },
        {
          title: "🎯 Strong learning culture",
          bullets: [
            "Free training for technical and soft skills",
            "Access to internal LMS with thousands of lectures",
            "Workshops, seminars, tech talks with internal and external experts",
          ],
        },
      ],
    },
  },
};

export const demoJobs: Job[] = [
  {
    id: "1",
    tenantId: demoTenant.id,
    title: "Senior Backend Engineer (Java/Spring Boot)",
    level: "Senior",
    type: "Full-Time",
    salary: "$2,500 - $4,000",
    company: "Engineering & Technology — Acme Co",
    location: "Hanoi, Vietnam",
    description:
      "We're hiring a senior backend engineer to lead the design and delivery of high-throughput services that power our recruitment platform.",
    requirements:
      "5+ years building production Java/Spring Boot services\nStrong Postgres / SQL fundamentals\nExperience with event-driven architectures and cloud (AWS/GCP)",
    benefits:
      "Competitive salary with 13th-month bonus\nPremium health insurance\nFlexible working hours, 1 remote day/month\nYearly company trip",
    isHot: true,
    displayOrder: 1,
    status: "published",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    tenantId: demoTenant.id,
    title: "Frontend Engineer (React / Next.js)",
    level: "Middle",
    type: "Full-Time",
    salary: "$1,500 - $2,500",
    company: "Engineering & Technology — Acme Co",
    location: "Hanoi, Vietnam",
    description: "",
    requirements: "",
    benefits: "",
    isHot: false,
    displayOrder: 2,
    status: "published",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    tenantId: demoTenant.id,
    title: "Blockchain Developer (Solidity)",
    level: "Senior",
    type: "Full-Time",
    salary: "Negotiable",
    company: "Engineering & Technology — Acme Co",
    location: "Ho Chi Minh, Vietnam",
    description: "",
    requirements: "",
    benefits: "",
    isHot: true,
    displayOrder: 3,
    status: "published",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    tenantId: demoTenant.id,
    title: "Product Marketing Specialist",
    level: "Junior",
    type: "Full-Time",
    salary: "$800 - $1,200",
    company: "Sales & Marketing — Acme Co",
    location: "Hanoi, Vietnam",
    description: "",
    requirements: "",
    benefits: "",
    isHot: false,
    displayOrder: 4,
    status: "published",
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    tenantId: demoTenant.id,
    title: "HR Business Partner",
    level: "Manager",
    type: "Full-Time",
    salary: "$2,000 - $3,000",
    company: "Back Office — Acme Co",
    location: "Hanoi, Vietnam",
    description: "",
    requirements: "",
    benefits: "",
    isHot: false,
    displayOrder: 5,
    status: "published",
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    tenantId: demoTenant.id,
    title: "DevOps Engineer (AWS / Kubernetes)",
    level: "Middle",
    type: "Full-Time",
    salary: "$1,800 - $2,800",
    company: "Engineering & Technology — Acme Co",
    location: "Ho Chi Minh, Vietnam",
    description: "",
    requirements: "",
    benefits: "",
    isHot: false,
    displayOrder: 6,
    status: "published",
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    tenantId: demoTenant.id,
    title: "Frontend Intern",
    level: "Intern",
    type: "Internship",
    salary: "Allowance",
    company: "Engineering & Technology — Acme Co",
    location: "Hanoi, Vietnam",
    description: "",
    requirements: "",
    benefits: "",
    isHot: false,
    displayOrder: 7,
    status: "published",
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    tenantId: demoTenant.id,
    title: "Customer Success Lead",
    level: "Leader",
    type: "Full-Time",
    salary: "$1,500 - $2,200",
    company: "Operation Support — Acme Co",
    location: "Da Nang, Vietnam",
    description: "",
    requirements: "",
    benefits: "",
    isHot: false,
    displayOrder: 8,
    status: "published",
    createdAt: new Date().toISOString(),
  },
];

export function isSupabaseConfigured(): boolean {
  return Boolean(
    process.env.NEXT_PUBLIC_SUPABASE_URL &&
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  );
}
